version:                "3"
services:
  datascience-notebook:
      image:            jupyter/datascience-notebook
      volumes:
        - C:\Users\lsham\Documents\data_science\house_prices:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container